config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  get 'tokyos/:tokyo_id/likes' => 'likes#create'
  get 'tokyos/:tokyo_id/likes/:id' => 'likes#destroy'
  root 'tokyos#index'
  resources :tokyos do
  end
  resources :likes, only: [:create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tokyo
  has_many :user
  validates_uniqueness_of :tokyo_id, scope: :user_id
end

app/models/tokyo.rb
class Tokyo < ApplicationRecord
    hasmany :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
  has_many :tokyos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tokyos, through: :likes, source: :tokyo

  def already_liked?(tokyo)
    self.likes.exists?(tokyo_id: tokyo.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tweet_id: params[:tweet_id])
        redirect_back(fallback_location: root_path)
    end
    
    def destroy
        like = Like.find_by(tokyo_id: params[:tokyo_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end
end

app/controllers/tokyos_controller.rb
class TokyosController < ApplicationController
    before_action :authenticate_user!

    def index
        @tokyos = tokyo.all
    end

    def new
        @tokyo = Tokyo.new
    end

    def create
        tokyo = Tokyo.new(tokyo_params)
        tokyo.user_id = current_user.id 
        if tokyo.save
            redirect_to :action => "top"
        else
            redirect_to :action => "new"
        end
    end

    def snow
        @tokyo = Tokyo.find(params[:id])
    end

    def edit
        @tokyo = Tokyo.find(params[:id])
    end

    def update
        tokyo = Tokyo.find(params[:id])
        if tokyo.update(tokyo_params)
            redirect_to :action => "show", :id => tokyo.id
        else
            redirect_to :action => "new"
        end
    end

    def destroy
        tokyo = Tokyo.find(params[:id])
        tokyo.destroy
        redirect_to action: :index
    end

    private
    def tokyo_params
        params.require(:tokyo).permit(:name, :unit, :lecture, :mentor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tokyos_helper.rb
module TokyosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tokyoerror</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/c1b1cd6975.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "GeekSalon Tokyo", tokyos_path %></h1>
      <div class= "user">
        <% if user_signed_in? %>
          <%= button_to "ログアウト", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "ログイン", tokyos_path %>
          <%= link_to "新規登録", new_user_registration_path %>
        <% end %>
      </div>
    </header>
    <%= yield %
  </body>
</html>

app/views/tokyos/edit.html.erb
<%= form_for @tokyos do |t| %>
    <%= f.label :氏名 %>
        <%= f.text_field :name,size: 40%>
    <br>
        <%= f.label :所属Unit %>
        <%= f.select :unit, 
        [["Unit1", "Unit1"], 
        ["Unit2", "Unit2"], 
        ["Unit3", "Unit3"]], include_blank: "選択して下さい" %>
    <br>
        <%= f.label :所属コース %>
        <%= f.select :course, 
        [["web", "web"], 
        ["iphone", "iphone"], 
        ["game", "game"], 
        ["python", "python"], 
        ["AI", "AI"], 
        ["webEX", "webEX"], 
        ["UIUX", "UIUX"], 
        ["VE", "VE"]], include_blank: "選択して下さい" %>
    <br>
        <%= f.label :担当メンター %>
        <%= f.text_field :mentor,size: 40%>
    <%= f.submit "編集する" %>
<% end %>

<%= link_to "一覧に戻る", tokyo_path %>

app/views/tokyos/index.html.erb
<h1>一覧ページ</h1>

▶<%= link_to "新規投稿へ", new_tokyo_path %>


<% @tokyos.each do |t| %>
    <div class="tokyos-container">
        <div class="column">
            <h3>氏名</h3>
            <p><%= t.name %></p>
        </div>
        <div class="column">
            <h3>所属unit</h3>
            <p><%= t.unit %></p>
        </div>
        <div class="column">
            <h3>コース</h3>
            <p><%= t.course %>
        </div>
        <div class="column">
            <h3>受講期</h3>
            <p><%= t.lecture %>期</p>
        </div>
        <div class="column">
            <h3>担当メンター</h3>
            <p><%= t.mentor %></p>
        </div>
        <div class="column">
            <%= link_to "詳細へ", tokyo_path(t.id) %> 
            <br>
            <% if user_signed_in? %>
                <% if current_user.already_liked?(t) %>
                    <%= link_to tokyo_like_path(id: t.id, tokyo_id: t.id), method: :delete do %>
                        💖<%= t.likes.count %>
                    <% end %>
                <% else %>
                    <%= link_to tokyo_likes_path(id: t.id, tokyo_id: t.id), method: :post do %>
                        💖<%= t.likes.count %>
                    <% end %>
                <% end %>
            <% else %>
                💖<%= t.likes.count %>
            <% end %>
        </div>
    </div>
<% end %>

app/views/tokyos/new.html.erb
<%= form_for(@tokyo, :url => { controller:'tokyos', action:'create'})do |f| %>
        <%= f.label :氏名 %>
        <%= f.text_field :name,size: 40%>
    <br>
        <%= f.label :所属Unit %>
        <%= f.select :unit, 
        [["Unit1", "Unit1"], 
        ["Unit2", "Unit2"], 
        ["Unit3", "Unit3"]], include_blank: "選択して下さい" %>
    <br>
        <%= f.label :所属コース %>
        <%= f.select :course, 
        [["web", "web"], 
        ["iphone", "iphone"], 
        ["game", "game"], 
        ["python", "python"], 
        ["AI", "AI"], 
        ["webEX", "webEX"], 
        ["UIUX", "UIUX"], 
        ["VE", "VE"]], include_blank: "選択して下さい" %>
    <br>
        <%= f.label :何か一言 %>
        <%= f.text_field :body,size: 40%>
        <%= f.submit %>
<% end %>

app/views/tokyos/show.html.erb
<div class="tokyo">
    <h1>投稿詳細</h1>
    <br>
    <br>
    <h3>氏名</h3>
        <p><%= @tokyo.name %></p>
    <h3>所属unit</h3>
        <p><%= @tokyo.unit %></p>
    <h3>所属コース</h3>
    <h3>担当メンター</h3>
        <p><%= @tokyo.mentor %></p>
    <br>
    <% if user_signed_in? %>
        <% if current_user.already_liked?(@tokyo) %>
            <%= link_to tokyo_like_path(@tokyo), method: :delete do %>
                <span>💖<%= t.likes.count %></span>
            <% end %>
        <% else %>
            <%= link_to tokyo_likes_path(@tokyo), method: :post do %>
                <span>💖<%= t.likes.count %></span>
            <% end %>
        <% end %>
    <% else %>
        <span>💖<%= t.likes.count %></span>
    <% end %>
    <br>
    <%= link_to "編集する", edit_tokyo_path(@tokyo.id) %>
    &nbsp;
    &nbsp;
    <%= link_to "一覧に戻る", tokyos_path %>
    &nbsp;
    &nbsp;
    <%= button_to "削除する", tokyo_path(@tokyo.id), method: :delete %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>